

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("[main] starting");


    Ok(())
}
